### ISSUE TITLE
The Voice

### ISSUE THREAD

**Issue by shertz43** [MiSTer-devel/Odyssey2_MiSTer#2]
Will this core implement 'The Voice' for games that use enhanced speech games?

**Comment by sav2880** [comment]
Might have found a case where The Voice isn't quite working yet, and of course, it's the one game I'm most wanting to mess with!

On Turtles! on the O2, The Voice module is used to play background music, two different tunes, during game play. This, to my knowledge, is the only game that does this as opposed to using it for actual synthetic voice. With The Voice turned on, when you hit the action button to first start a game, you hear a short "buzz" that is consistent with the music starting as soon as the level starts. However, when you get into actual gameplay, there is no music. 

My counter-test to this was to run Smithereens and make sure voice worked there, which it did (and didn't with the module turned off, all on the fly) as a sanity check since I do not have the original hardware on hand currently. Can provide more info, may even do a quick private video to better show it over capture.

**Comment by G7200** [comment]
Be patient, on Turtles the voice will sing soon ;)

**Comment by rampa069** [comment]
Can you please update and re-check turtles? ;-)

**Comment by sav2880** [comment]
Sounds absolutely beautiful! Thank you!!

**Comment by rampa069** [comment]
Thank you for reporting!
